package org.ds.rps.interfaces;


/**
* org/ds/rps/interfaces/_CallBackImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameInterfaces.idl
* 29 March 2015 22:08:29 o'clock IST
*/


//Callback
public abstract class _CallBackImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements org.ds.rps.interfaces.CallBack, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _CallBackImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("message", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // org/ds/rps/interfaces/CallBack/message
       {
         String msg = in.read_string ();
         this.message (msg);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:org/ds/rps/interfaces/CallBack:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _CallBackImplBase
