package org.ds.rps.interfaces;


/**
* org/ds/rps/interfaces/CallBack_Tie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameInterfaces.idl
* 29 March 2015 22:08:29 o'clock IST
*/


//Callback
public class CallBack_Tie extends _CallBackImplBase
{

  // Constructors
  public CallBack_Tie ()
  {
  }

  public CallBack_Tie (org.ds.rps.interfaces.CallBackOperations impl)
  {
    super ();
    _impl = impl;
  }

  public void message (String msg)
  {
    _impl.message(msg);
  } // message

  private org.ds.rps.interfaces.CallBackOperations _impl;

} // class CallBack_Tie
