package org.ds.rps.interfaces;


/**
* org/ds/rps/interfaces/CallBackOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameInterfaces.idl
* 29 March 2015 22:08:29 o'clock IST
*/


//Callback
public interface CallBackOperations 
{
  void message (String msg);
} // interface CallBackOperations
