package org.ds.rps.interfaces;


/**
* org/ds/rps/interfaces/create_fail.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameInterfaces.idl
* 29 March 2015 22:08:29 o'clock IST
*/

public final class create_fail extends org.omg.CORBA.UserException
{

  public create_fail ()
  {
    super(create_failHelper.id());
  } // ctor


  public create_fail (String $reason)
  {
    super(create_failHelper.id() + "  " + $reason);
  } // ctor

} // class create_fail
