package org.ds.rps.interfaces;


/**
* org/ds/rps/interfaces/destroy_fail.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameInterfaces.idl
* 29 March 2015 22:08:29 o'clock IST
*/

public final class destroy_fail extends org.omg.CORBA.UserException
{

  public destroy_fail ()
  {
    super(destroy_failHelper.id());
  } // ctor


  public destroy_fail (String $reason)
  {
    super(destroy_failHelper.id() + "  " + $reason);
  } // ctor

} // class destroy_fail
