package org.ds.rps.interfaces;


/**
* org/ds/rps/interfaces/GameInterfaceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameInterfaces.idl
* 29 March 2015 22:08:29 o'clock IST
*/

abstract public class GameInterfaceHelper
{
  private static String  _id = "IDL:org/ds/rps/interfaces/GameInterface:1.0";

  public static void insert (org.omg.CORBA.Any a, org.ds.rps.interfaces.GameInterface that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static org.ds.rps.interfaces.GameInterface extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (org.ds.rps.interfaces.GameInterfaceHelper.id (), "GameInterface");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static org.ds.rps.interfaces.GameInterface read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_GameInterfaceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, org.ds.rps.interfaces.GameInterface value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static org.ds.rps.interfaces.GameInterface narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof org.ds.rps.interfaces.GameInterface)
      return (org.ds.rps.interfaces.GameInterface)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      org.ds.rps.interfaces._GameInterfaceStub stub = new org.ds.rps.interfaces._GameInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static org.ds.rps.interfaces.GameInterface unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof org.ds.rps.interfaces.GameInterface)
      return (org.ds.rps.interfaces.GameInterface)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      org.ds.rps.interfaces._GameInterfaceStub stub = new org.ds.rps.interfaces._GameInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
