package org.ds.rps.interfaces;


/**
* org/ds/rps/interfaces/Game.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameInterfaces.idl
* 29 March 2015 22:08:29 o'clock IST
*/

public final class Game implements org.omg.CORBA.portable.IDLEntity
{
  public String id = null;
  public String date = null;
  public String winner_id = null;
  public String winner_name = null;
  public String message = null;
  public boolean isActive = false;
  public org.ds.rps.interfaces.Player players[] = null;

  public Game ()
  {
  } // ctor

  public Game (String _id, String _date, String _winner_id, String _winner_name, String _message, boolean _isActive, org.ds.rps.interfaces.Player[] _players)
  {
    id = _id;
    date = _date;
    winner_id = _winner_id;
    winner_name = _winner_name;
    message = _message;
    isActive = _isActive;
    players = _players;
  } // ctor

} // class Game
