package org.ds.rps.interfaces;


/**
* org/ds/rps/interfaces/PlayerHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameInterfaces.idl
* 29 March 2015 22:08:29 o'clock IST
*/

abstract public class PlayerHelper
{
  private static String  _id = "IDL:org/ds/rps/interfaces/Player:1.0";

  public static void insert (org.omg.CORBA.Any a, org.ds.rps.interfaces.Player that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static org.ds.rps.interfaces.Player extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [6];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "id",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "name",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[2] = new org.omg.CORBA.StructMember (
            "score",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.ds.rps.interfaces.RPSHelper.type ();
          _members0[3] = new org.omg.CORBA.StructMember (
            "choice",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_boolean);
          _members0[4] = new org.omg.CORBA.StructMember (
            "isReady",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.ds.rps.interfaces.CallBackHelper.type ();
          _members0[5] = new org.omg.CORBA.StructMember (
            "callback",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (org.ds.rps.interfaces.PlayerHelper.id (), "Player", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static org.ds.rps.interfaces.Player read (org.omg.CORBA.portable.InputStream istream)
  {
    org.ds.rps.interfaces.Player value = new org.ds.rps.interfaces.Player ();
    value.id = istream.read_string ();
    value.name = istream.read_string ();
    value.score = istream.read_long ();
    value.choice = org.ds.rps.interfaces.RPSHelper.read (istream);
    value.isReady = istream.read_boolean ();
    value.callback = org.ds.rps.interfaces.CallBackHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, org.ds.rps.interfaces.Player value)
  {
    ostream.write_string (value.id);
    ostream.write_string (value.name);
    ostream.write_long (value.score);
    org.ds.rps.interfaces.RPSHelper.write (ostream, value.choice);
    ostream.write_boolean (value.isReady);
    org.ds.rps.interfaces.CallBackHelper.write (ostream, value.callback);
  }

}
