package org.ds.rps.interfaces;


/**
* org/ds/rps/interfaces/PlayerListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameInterfaces.idl
* 29 March 2015 22:08:29 o'clock IST
*/


//Array of players
public final class PlayerListHolder implements org.omg.CORBA.portable.Streamable
{
  public org.ds.rps.interfaces.Player value[] = null;

  public PlayerListHolder ()
  {
  }

  public PlayerListHolder (org.ds.rps.interfaces.Player[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.ds.rps.interfaces.PlayerListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.ds.rps.interfaces.PlayerListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.ds.rps.interfaces.PlayerListHelper.type ();
  }

}
