package org.ds.rps.interfaces;


/**
* org/ds/rps/interfaces/RPS.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameInterfaces.idl
* 29 March 2015 22:08:29 o'clock IST
*/


//RPS values
public class RPS implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 4;
  private static org.ds.rps.interfaces.RPS[] __array = new org.ds.rps.interfaces.RPS [__size];

  public static final int _unselected = 0;
  public static final org.ds.rps.interfaces.RPS unselected = new org.ds.rps.interfaces.RPS(_unselected);
  public static final int _rock = 1;
  public static final org.ds.rps.interfaces.RPS rock = new org.ds.rps.interfaces.RPS(_rock);
  public static final int _paper = 2;
  public static final org.ds.rps.interfaces.RPS paper = new org.ds.rps.interfaces.RPS(_paper);
  public static final int _scissor = 3;
  public static final org.ds.rps.interfaces.RPS scissor = new org.ds.rps.interfaces.RPS(_scissor);

  public int value ()
  {
    return __value;
  }

  public static org.ds.rps.interfaces.RPS from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected RPS (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class RPS
