package org.ds.rps.interfaces;


/**
* org/ds/rps/interfaces/unknown_path.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameInterfaces.idl
* 29 March 2015 22:08:29 o'clock IST
*/

public final class unknown_path extends org.omg.CORBA.UserException
{

  public unknown_path ()
  {
    super(unknown_pathHelper.id());
  } // ctor


  public unknown_path (String $reason)
  {
    super(unknown_pathHelper.id() + "  " + $reason);
  } // ctor

} // class unknown_path
