package org.ds.rps.interfaces;


/**
* org/ds/rps/interfaces/unknown_player.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameInterfaces.idl
* 29 March 2015 22:08:29 o'clock IST
*/

public final class unknown_player extends org.omg.CORBA.UserException
{

  public unknown_player ()
  {
    super(unknown_playerHelper.id());
  } // ctor


  public unknown_player (String $reason)
  {
    super(unknown_playerHelper.id() + "  " + $reason);
  } // ctor

} // class unknown_player
